apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: http-deploy-b
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: http-app
        color: blue
    spec:
      containers:
        - name: nginx
          image: docker.io/jocatalin/kubernetes-bootcamp:v1
          ports:
            - name: http-port
              containerPort: 8080
      volumes:
        - name: docroot
          emptyDir: {}
