kind: Service
apiVersion: v1
metadata:
  name: http-service
spec:
  selector:
    app: http-app
    color: blue
  ports:
    - port: 8080
      targetPort: http-port
  externalIPs:
    - 192.168.99.100
